name: magical_version_bump
description: A Very Good Project created to automatically modify/change the version 
  specified in your pubspec.yaml
version: 0.0.1-dev.3
homepage: https://github.com/kekavc24/magical_version_bump
repository: https://github.com/kekavc24/magical_version_bump
issue_tracker: https://github.com/kekavc24/magical_version_bump/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.3.0
  mason_logger: ^0.2.4
  pub_updater: ^0.3.0
  pubspec_parse: ^1.2.2
  yaml: ^3.1.1
  yaml_edit: ^2.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1

executables:
  mag:
