name: magical_version_bump
description: A commandline tool for automatically modifying/changing nodes
  specified in your pubspec.yaml
version: 1.1.0-dev.1
homepage: https://github.com/kekavc24/magical_version_bump
repository: https://github.com/kekavc24/magical_version_bump
issue_tracker: https://github.com/kekavc24/magical_version_bump/issues
topics:
  - cli
  - version
  - pubspec
  - json
  - yaml

environment:
  sdk: ^3.6.0

platforms:
  linux:
  windows:
  macos:

dependencies:
  args: ^2.4.2
  collection: ^1.19.1
  mason_logger: ^0.3.1
  meta: ^1.11.0
  petitparser: ^6.0.2
  pub_updater: ^0.5.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  build_version: ^2.1.1
  checks: ^0.3.0
  test: ^1.25.2
  very_good_analysis: ^7.0.0

executables:
  mag:
