name: update pubspec.yaml and verify version

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    pull_request:
      branches: [ "master" ]
      types: [closed]
  
jobs:
    update-version:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.ref }}
            fetch-depth: 0
            token: ${{ secrets.VERSION_VERIFY }}
            
        - name: 🌽 Corn-figure Git ;)
          id: corn-fig-git
          uses: crazy-max/ghaction-import-gpg@v5
          with: 
            gpg_private_key: ${{ secrets.BOT_GPG_KEY }}
            git_config_global: true
            git_user_signingkey: true
            git_commit_gpgsign: true

        - name: 🎯 Setup Dart
          uses: dart-lang/setup-dart@v1
          with:
            sdk: "stable"

        - name: ⚡ Activate Magical Bump CLI
          run: dart pub global activate --source=path .
        
        - name: ➕ Bump major version
          if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'major release')) }}
          run: |
            mag modify -b --major
            git commit -am "chore(deps): bump major version"
            git push
          env:
            GIT_AUTHOR_NAME: ${{ steps.corn-fig-git.outputs.name }}
            GIT_AUTHOR_EMAIL: ${{ steps.corn-fig-git.outputs.email }}
            GIT_COMMITTER_NAME: ${{ steps.corn-fig-git.outputs.name }}
            GIT_COMMITTER_EMAIL: ${{ steps.corn-fig-git.outputs.email }}
        
        - name: ➕ Bump minor version
          if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'minor release')) }}
          run: |
            mag modify -b --minor
            git commit -am "chore(deps): bump minor version"
            git push
          env:
            GIT_AUTHOR_NAME: ${{ steps.corn-fig-git.outputs.name }}
            GIT_AUTHOR_EMAIL: ${{ steps.corn-fig-git.outputs.email }}
            GIT_COMMITTER_NAME: ${{ steps.corn-fig-git.outputs.name }}
            GIT_COMMITTER_EMAIL: ${{ steps.corn-fig-git.outputs.email }}
          
        - name: ➕ Bump patch version
          if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'patch release')) }}
          run: |
            mag modify -b --patch
            git commit -am "chore(deps): bump patch version"
            git push
          env:
            GIT_AUTHOR_NAME: ${{ steps.corn-fig-git.outputs.name }}
            GIT_AUTHOR_EMAIL: ${{ steps.corn-fig-git.outputs.email }}
            GIT_COMMITTER_NAME: ${{ steps.corn-fig-git.outputs.name }}
            GIT_COMMITTER_EMAIL: ${{ steps.corn-fig-git.outputs.email }}
  
        - name: 🧬 Generate new asset graph
          if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'publish')) }}
          run: |
            dart run build_runner build --delete-conflicting-outputs
            git commit -am "chore(build): generated new asset graph"
            git push
          env:
            GIT_AUTHOR_NAME: ${{ steps.corn-fig-git.outputs.name }}
            GIT_AUTHOR_EMAIL: ${{ steps.corn-fig-git.outputs.email }}
            GIT_COMMITTER_NAME: ${{ steps.corn-fig-git.outputs.name }}
            GIT_COMMITTER_EMAIL: ${{ steps.corn-fig-git.outputs.email }}

    verify-version:
        needs: update-version
        runs-on: ubuntu-latest
        steps:
            -   name: 📚 Git Checkout
                uses: actions/checkout@v3
                with:
                  fetch-depth: 0
                  token: ${{ secrets.VERSION_VERIFY }}

            -   name: 🎯 Setup Dart
                uses: dart-lang/setup-dart@v1
                with:
                  sdk: "stable"

            -   name: 📦 Install & Configure Dependencies
                run: |  
                  git pull
                  dart pub get
            
            -   name: 🔎 Verify version
                if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'publish')) }}
                run: dart run test --run-skipped -t version-verify
            
